apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: training
  region: eu-west-1

managedNodeGroups:
  - name: ng-1
    labels: { role: regulars }
    instanceType: c5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    tags:
      nodegrouprole: test
    volumeSize: 20
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        awsLoadBalancerController: true
        albIngress: true
        autoScaler: true
        ebs: true
        efs: true
        imageBuilder: true
        appMesh: true
        xRay: true
        cloudWatch: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

