apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-1

managedNodeGroups:
  - name: ng-1
    labels: { role: regulars }
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    tags:
      nodegrourole: test
    volumeSize: 20
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        awsLoadBalancerController: true
        albIngress: true
        autoScaler: true
        ebs: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

